### PR TITLE
Class name proposal.

### PR DESCRIPTION
**Pull request by jcricaro**
Would love to use this in production.

### CODE REVIEW

**Comment by rmrhz** [comment]
Hahahaha, this would break the whole package.

**Comment by daison12006013** [comment]
There is no basis that it will break the whole package, this must have some unit testing for us to see it through the problem and fix things out.

There must also a develop branch.

**Comment by rmrhz** [comment]
> There is no basis that it will break the whole package

Bruh. It would break the whole idea of the package. Lastly, I found no need to publish a develop branch yet as documentation isn't implemented yet. Everything is subject to change prior to that.

**Comment by rmrhz** [comment]
I'm sorry but I'll have to close this down. The name `Repofuck` renames. If I have to submit to future compromises because something will trigger them by the time they read it. Then those people should know that's the essence of opensource

**Pull request closed without merging**
